[package]
name = "pineapple-launcher"
version = "0.1.0"
edition = "2021"
description = "Pineapple OS — lançador de aplicativos"
license = "GPL-3.0"

[dependencies]
gtk = { package = "gtk4", version = "0.8" }
gtk4-layer-shell = "0.3"
glib = "0.19"
gio = "0.19"

[[bin]]
name = "pineapple-launcher"
path = "src/main.rs"
