---
# =============================================================================
#  Calamares — settings.conf do Pineapple OS
# =============================================================================
modules-search:
  - local

instances:
  - id:       pineappleos-branding
    module:   branding
    config:   branding.desc
  - id:       pineappleos-packages
    module:   packages
    config:   packages.conf
  - id:       pineappleos-shellprocess
    module:   shellprocess
    config:   shellprocess.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
    - networkcfg
      - partition
      - users
      - summary
  - exec:
      - partition
      - users
    - locale
    - keyboard
    - networkcfg
      - pineappleos-packages
      - pineappleos-shellprocess
  - show:
      - finish

branding: pineappleos-branding

dont-chroot: false
