---
# =============================================================================
#  Calamares — settings.conf do Mak OS
# =============================================================================
modules-search:
  - local

instances:
  - id:       makos-branding
    module:   branding
    config:   branding.desc
  - id:       makos-packages
    module:   packages
    config:   packages.conf
  - id:       makos-shellprocess
    module:   shellprocess
    config:   shellprocess.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - users
      - makos-packages
      - makos-shellprocess
  - show:
      - finish

branding: makos-branding

dont-chroot: false
