[package]
name = "pineapple-shell"
version = "0.1.0"
edition = "2021"
description = "Pineapple OS — barra superior e shell do sistema"
license = "GPL-3.0"

[dependencies]
gtk = { package = "gtk4", version = "0.8" }
gtk4-layer-shell = "0.3"
glib = "0.19"
gio = "0.19"
libadwaita = { version = "0.6", features = ["v1_4"] }
zbus = "4"
futures-util = "0.3"
chrono = "0.4"
libc = "0.2"

[[bin]]
name = "pineapple-shell"
path = "src/main.rs"

[[bin]]
name = "pineapple-session"
path = "src/bin/pineapple-session.rs"
